D&D 4e Compatibility
kandashi/Active-Auras pull request #265
Opened 2023-02-08 05:01 UTC by FoxLee

Hiya, I hope you don't mind but I took the liberty of adding some code to improve Active Auras' compatibility with D&D 4e (there are _dozens_ of us! :p). Since the 4e Foundry implementation is built using 5e as a base, AA functions quite well out of the box, but there are some specifics that benefited from additional tweaks. Specifically, I've added 4e to the lists of systems to check for non-Euclidean diagonals as is its default, and I've added a 4e-specific type check function to let us apply auras based on creature origin, type and subtype.

2023-02-15 09:13 UTC, MrPrimate requested changes

2023-02-15 09:13 UTC, MrPrimate commented on src/AAhelpers.js
> +            case ("dnd4e"):
This would run the `typeCheck4e` function for the 5e and 4e system - could you move the 4e case check to below swade?

2023-02-16 04:36 UTC, FoxLee commented on src/AAhelpers.js
> +            case ("dnd4e"):
Oh of course. Sorry about that! I really need to use JS more often.

2023-02-16 07:48 UTC, MrPrimate commented
Thanks!

2023-02-16 07:49 UTC, merged